export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const PRODUCTS_ADDED = 'PRODUCTS_ADDED'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'

export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
export const PRODUCTS_DELETED = 'PRODUCTS_DELETED'
